# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

parameters:
  - name: system
    type: string
    values:
      - "ubuntu-latest"
      - "macOS-11"


jobs: 
- job:
  pool:
    vmImage: ${{ parameters.system }}
  steps:
  - checkout: self
    fetchDepth: 1
    fetchTags: false
    displayName: Clone repository
  
  - ${{ if contains(parameters.system, 'macOS') }}:
    - bash: |
  
        echo -e "\n[+] Install plugin dependencies\n "
        yarn install
  
        echo -e "\n[+] Install iOS dependencies\n"
        cd example/ios
  
        pod install
  
      displayName: Install iOS dependencies
  
  
  - ${{ if contains(parameters.system, 'ubuntu') }}:
    - bash: |
  
        echo -e "\n[+] Install plugin dependencies\n "
        npm install
  
        echo -e "\n[+] Install Android dependencies\n"
        cd example/android
        npm install
        
  
      displayName: Install Android dependencies
