# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - feature/*

pr: none

parameters:
  - name: XAPIEMAIL
    type: string
    displayName: X-API-EMAIL
    default: user@email.com
  - name: XAPIKEY
    type: string
    displayName: X-API-KEY
    default: user-api-key
  - name: BUILDINGID
    type: string
    default: "1"
  - name: FLOORID
    type: string
    default: "1"
  - name: DASHBOARD_URL
    type: string
    default: "https://dashboard.situm.com"

variables:
  - group: Passwords
  - group: SoftwareVersions

resources:
  repositories:
  - repository: sys_kubernetes_templates
    type: bitbucket
    endpoint: Bitbucket - sistemas
    name: situm/sys-kubernetes-templates.git

jobs: 
  - job:
    displayName: Build Android App
    pool:
      vmImage: $(ubuntuVersion)
    steps:
    - template: azure/common-steps.yaml

    - ${{ if eq(variables['Build.Reason'],'manual') }}:
       - template: azure/build-examples.yaml
         parameters:
           XAPIKEY: ${{ parameters.XAPIKEY }}
           XAPIEMAIL: ${{ parameters.XAPIEMAIL }}
           BUILDINGID: ${{ parameters.BUILDINGID }}
           FLOORID: ${{ parameters.FLOORID }}
           DASHBOARD_URL: ${{ parameters.DASHBOARD_URL }}
           system: ${{ parameters.system }}
    
    - ${{ if ne(variables['Build.Reason'],'manual') }}:
       - template: azure/build-examples.yaml
         parameters:
           XAPIKEY: $(XAPIKEY_EXAMPLES)
           XAPIEMAIL: $(XAPIEMAIL_EXAMPLES)
           BUILDINGID: $(BUILDING_ID_EXAMPLES)
           FLOORID: $(FLOOR_ID_EXAMPLES)
           DASHBOARD_URL: "https://dashboard.situm.com"
           system: ${{ parameters.system }}
  
  - job:
    displayName: Build iOS App
    pool:
      vmImage: $(macOSVersion)
    steps:
    - template: azure/common-steps.yaml
    - ${{ if eq(variables['Build.Reason'],'manual') }}:
       - template: azure/build-examples.yaml
         parameters:
           XAPIKEY: ${{ parameters.XAPIKEY }}
           XAPIEMAIL: ${{ parameters.XAPIEMAIL }}
           BUILDINGID: ${{ parameters.BUILDINGID }}
           FLOORID: ${{ parameters.FLOORID }}
           DASHBOARD_URL: ${{ parameters.DASHBOARD_URL }}
           system: ${{ parameters.system }}
    
    - ${{ if ne(variables['Build.Reason'],'manual') }}:
       - template: azure/build-examples.yaml
         parameters:
           XAPIKEY: $(XAPIKEY_EXAMPLES)
           XAPIEMAIL: $(XAPIEMAIL_EXAMPLES)
           BUILDINGID: $(BUILDING_ID_EXAMPLES)
           FLOORID: $(FLOOR_ID_EXAMPLES)
           DASHBOARD_URL: "https://dashboard.situm.com"
           system: ${{ parameters.system }}

