# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

parameters:
  - name: system
    type: string
    values:
      - "ubuntu-latest"
      - "macOS-11"


jobs: 
- job:
  pool:
    vmImage: ${{ parameters.system }}
  steps:
  - checkout: self
    fetchDepth: 1
    fetchTags: false
    displayName: Clone repository

  - bash: |

      echo -e "\n[+] Install plugin dependencies\n"
      npm install

      echo -e "\n[+] Install example dependencies\n"
      cd example
      npm install

    displayName: Install plugin dependencies
  
  - ${{ if contains(parameters.system, 'macOS') }}:
    - bash: |
        echo -e "\n[+] Install iOS example dependencies\n"
        cd example/ios
        pod install
      displayName: Install iOS example dependencies

    - bash: |

        cd example/ios/fastlane

        echo -e "\n[+] Install fastlane \n"
        gem install fastlane

        echo -e "\n[+] Build example with fastlane \n"
        fastlane ios beta

      displayName: Build iOS example 
  
  
  - ${{ if contains(parameters.system, 'ubuntu') }}:
    - bash: |
 
        echo -e "\n[+] Build Android example \n"
        cd example/android

        ./gradlew assembleDebug

        cd app/build/outputs/apk/debug

        ls -lahrt
        
      displayName: Build Android dependencies
