# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: RNVersion
    type: string
    displayName: React Native Plugin Version

variables:
  - group: Passwords

resources:
  repositories:
  - repository: sys_kubernetes_templates
    type: bitbucket
    endpoint: Bitbucket - sistemas
    name: situm/sys-kubernetes-templates.git

steps:
- ${{ if contains(variables['Build.SourceBranch'], 'feature/') }}:
  - checkout: self
    fetchDepth: 1
    fetchTags: false
    displayName: Checkout self

  - bash: |
      echo "##vso[task.setvariable variable=version]$(echo ${{ parameters.RNVersion }})"
      currentBranch=$(echo $(Build.SourceBranch) | cut -d "/" -f 3,4)
      echo "##vso[task.setvariable variable=currentBranch]$(echo $currentBranch)
      echo -e "\n[+] Defined versions:"
      echo -e "\t[+] NPM cli version: $(npm --version)" 
      echo -e "\t[+] React Native Plugin version: ${{ parameters.RNVersion }}"
      echo -e "\t[+] Current branch: $currentBranch"

        
      echo -e "\n[+] Setting git remote credentials\n"
      git remote set-url origin https://situmops:$(github_token)@github.com/$(Build.Repository.Name).git
      cat .git/config

    displayName: Initial Vars & Configs

  - bash: |

      echo -e "\n[+] Setting NPM version to $(version)"
      npm version $(version) --no-git-tag-version

      echo -e "\n[+] Configure RELEASE.md changes"
      sed -i -e '/guidelines/rCHANGELOG_UNRELEASED.md' CHANGELOG.md 
      sed -i '/^#.*Unreleased/d' CHANGELOG.md
      echo '# [Unreleased]' > CHANGELOG_UNRELEASED.md          

      echo -e "\n[+] Setting git to push NPM version\n"
      git config --global user.email "sistemas@situm.es"
      git config --global user.name "Situmops"

      echo -e "\n[+] Fetch branches \n"
      git fetch

      echo -e "\n[+] Changing to $(currentBranch)"
      git checkout $(currentBranch)

      echo -e "\n[+] Add,Commit and Push to $(currentBranch)"
      git commit -am "Setting the NPM version to $(version)"
      git push --set-upstream origin $(currentBranch)
      git push
    displayName: Make changes


  - template: azure-templates/publish_release.yml@sys_kubernetes_templates
    parameters:
      bitbucket:
        bitbucket_user: situmops
      system: "N/A"
      server: "github"
      mergeBranches:
        - "develop-SIS-614"
     

 

