# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: RNVersion
    type: string
    displayName: React Native Plugin Version

variables:
  - group: Passwords
steps:
- ${{ if contains(variables['Build.SourceBranch'], 'feature/') }}:
  - checkout: self
    displayName: Checkout self

  - bash: |
      echo "##vso[task.setvariable variable=version]$(echo ${{ parameters.RNVersion }})"
      currentBranch=$(echo $(Build.SourceBranch) | cut -d "/" -f 3,4)
      echo -e "\n[+] Defined versions:"
      echo -e "\t[+] NPM cli version: $(npm --version)" 
      echo -e "\t[+] React Native Plugin version: ${{ parameters.RNVersion }}"
      echo -e "\t[+] Current branch: $currentBranch"

        
      echo -e "\n[+] Setting git remote credentials\n"
      git remote set-url origin https://situmops:$(github_token)@github.com/$(Build.Repository.Name).git
      cat .git/config

      echo -e "\n[+] Setting NPM version to ${{ parameters.RNVersion }}"
      npm version ${{ parameters.RNVersion }} --no-git-tag-version

      echo -e "\n[+] Setting git to push NPM version\n"
      git config --global user.email "sistemas@situm.es"
      git config --global user.name "Situm Devops"

      git checkout $currentBranch
      git commit -am "Setting the NPM version to ${{ parameters.RNVersion }}"
      git push --set-upstream origin $currentBranch  
      git push

    displayName: Initial Vars & Configs

      #   - template: azure-templates/publish_release.yml@sys_kubernetes_templates
      #     parameters:
      #       bitbucket:
      #         bitbucket_user: situmops
      #       system: "N/A"
      #       server: "github"
      #       mergeBranches:
      #         - "develop-SIS-614"
      #     

 

